apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: analytics
      port: 9000
      server: db
      username: $GRAFANA_CH_USER
      tlsSkipVerify: false
    secureJsonData:
      password: $GRAFANA_CH_PASSWORD
